stages:
    - test
    - build

test:
    image: python:3
    stage: test
    script:
        - pip3 install --upgrade pytest
        - python3 -m pytest src/tests/test.py --junitxml=report.xml
    artifacts:
        when: always
        reports:
            junit: report.xml
        expire_in: 2 weeks    

package:
    image: python:3
    stage: build
    script:
        - pip3 install --upgrade build twine
        - python -m build
        - python3 -m twine upload dist/*
    rules:
        - if: '$CI_COMMIT_BRANCH == "prod"'
        - changes:
            - src/*
            - pyproject.toml
            - requirements.txt
pages:
    image: python:3
    stage: build
    variables:
        GIT_DEPTH: 1000
    script:
        - pip3 install --upgrade mkdocs "mkdocstrings[python]" mkdocs-material mkdocs-git-authors-plugin
        - cp README.md docs/index.md
        - mkdocs build -d public/
    artifacts:
        paths:
            - public
    rules:
        - if: '$CI_COMMIT_BRANCH == "prod"'

