package:
    image: python:3
    script:
        - pip3 install --upgrade build twine
        - python -m build
        - python3 -m twine upload dist/*
    rules:
        - if: '$CI_COMMIT_BRANCH == "prod"'
pages:
    image: python:3
    variables:
        GIT_DEPTH: 1000
    script:
        - pip3 install --upgrade mkdocs "mkdocstrings[python]" mkdocs-material mkdocs-git-authors-plugin
        - mkdocs build -d public/
    artifacts:
        paths:
            - public
    rules:
        - if: '$CI_COMMIT_BRANCH == "prod"'

