stages:
    - test
    - build
    - prepare
    - release

test:
    image: python:3
    stage: test
    script:
        - pip3 install --upgrade pytest python-dotenv mypy types-requests
        - pip3 install --upgrade -r requirements.txt
        - mypy --non-interactive src/ogsapi/. --junit-xml typetest.xml
        - python3 -m pytest src/tests/test.py --junitxml=report.xml
    artifacts:
        when: always
        paths:
            - report.xml
            - typetest.xml
        reports:
            junit: 
                - report.xml
                - typetest.xml
        expire_in: 2 weeks    

package:
    image: python:3
    stage: build
    script:
        - pip3 install --upgrade build twine
        - python -m build
        - python3 -m twine upload dist/*
    rules:
        - if: '$CI_COMMIT_BRANCH == "prod"'
          changes:
            - src/*
            - pyproject.toml
            - requirements.txt
pages:
    image: python:3
    stage: build
    variables:
        GIT_DEPTH: 1000
    script:
        - pip3 install --upgrade mkdocs "mkdocstrings[python]" mkdocs-material mkdocs-git-authors-plugin
        - cp README.md docs/index.md
        - cp CHANGELOG.md docs/changelog.md
        - mkdocs build -d public/
    artifacts:
        paths:
            - public
    rules:
        - if: '$CI_COMMIT_BRANCH == "prod"'

prepare_release:
    stage: prepare
    script:
        - echo "RELEASE_NUMBER=$(echo $CI_COMMIT_TAG | sed 's/v//')" >> variables.env
    artifacts:
        reports:
            dotenv: variables.env
    rules:
        - if: $CI_COMMIT_TAG

create_release:
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    needs:
        - job: prepare_release
          artifacts: true
    script:
        - echo "creating GitLab Release for $CI_COMMIT_TAG"
    release:
        tag_name: '$CI_COMMIT_TAG'
        description: '$CI_COMMIT_TAG_MESSAGE'
        ref: '$CI_COMMIT_SHA'
        assets:
            links:
                - name: 'PyPI Package'
                  url: 'https://pypi.org/project/ogsapi/$RELEASE_NUMBER/' 
                  link_type: 'package'
    rules:
        - if: $CI_COMMIT_TAG