name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set Changelog Message
        run: |
          echo "CHANGELOG=$(python get_release_msg.py)" >> $GITHUB_ENV  
      - uses: ncipollo/release-action@v1
        with:
          body: ${{ CHANGELOG }}